name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - libgfortran5
  - mesalib
  - scipy
  - pip:
      - cmeel_casadi_kin_dyn
      - darli
      - mujoco
      - mediapy
